// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type OpenatArgsT struct {
	_        structs.HostLayout
	Dfd      int32
	Flags    int32
	Filename [256]int8
}

// LoadOpenat returns the embedded CollectionSpec for Openat.
func LoadOpenat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpenatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Openat: %w", err)
	}

	return spec, err
}

// LoadOpenatObjects loads Openat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*OpenatObjects
//	*OpenatPrograms
//	*OpenatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadOpenatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadOpenat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// OpenatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenatSpecs struct {
	OpenatProgramSpecs
	OpenatMapSpecs
	OpenatVariableSpecs
}

// OpenatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenatProgramSpecs struct {
	TracepointSyscallsSysEnterOpenat *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysExitOpenat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_openat"`
}

// OpenatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenatMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	TmpStorage *ebpf.MapSpec `ebpf:"tmp_storage"`
}

// OpenatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenatVariableSpecs struct {
}

// OpenatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenatObjects struct {
	OpenatPrograms
	OpenatMaps
	OpenatVariables
}

func (o *OpenatObjects) Close() error {
	return _OpenatClose(
		&o.OpenatPrograms,
		&o.OpenatMaps,
	)
}

// OpenatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenatMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	TmpStorage *ebpf.Map `ebpf:"tmp_storage"`
}

func (m *OpenatMaps) Close() error {
	return _OpenatClose(
		m.Events,
		m.TmpStorage,
	)
}

// OpenatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenatVariables struct {
}

// OpenatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenatPrograms struct {
	TracepointSyscallsSysEnterOpenat *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysExitOpenat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_openat"`
}

func (p *OpenatPrograms) Close() error {
	return _OpenatClose(
		p.TracepointSyscallsSysEnterOpenat,
		p.TracepointSyscallsSysExitOpenat,
	)
}

func _OpenatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed openat_bpfeb.o
var _OpenatBytes []byte
