// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type OpenatExecveArgsT struct {
	_        structs.HostLayout
	Filename [256]int8
}

type OpenatOpenatArgsT struct {
	_        structs.HostLayout
	Dfd      int32
	Flags    int32
	Filename [256]int8
}

// LoadOpenat returns the embedded CollectionSpec for Openat.
func LoadOpenat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpenatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Openat: %w", err)
	}

	return spec, err
}

// LoadOpenatObjects loads Openat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*OpenatObjects
//	*OpenatPrograms
//	*OpenatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadOpenatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadOpenat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// OpenatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenatSpecs struct {
	OpenatProgramSpecs
	OpenatMapSpecs
	OpenatVariableSpecs
}

// OpenatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenatProgramSpecs struct {
	TraceEnterExecve *ebpf.ProgramSpec `ebpf:"trace_enter_execve"`
	TraceEnterOpenat *ebpf.ProgramSpec `ebpf:"trace_enter_openat"`
	TraceExitExecve  *ebpf.ProgramSpec `ebpf:"trace_exit_execve"`
	TraceExitOpenat  *ebpf.ProgramSpec `ebpf:"trace_exit_openat"`
}

// OpenatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenatMapSpecs struct {
	ExecveEvents     *ebpf.MapSpec `ebpf:"execve_events"`
	ExecveTmpStorage *ebpf.MapSpec `ebpf:"execve_tmp_storage"`
	OpenatEvents     *ebpf.MapSpec `ebpf:"openat_events"`
	OpenatTmpStorage *ebpf.MapSpec `ebpf:"openat_tmp_storage"`
}

// OpenatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenatVariableSpecs struct {
}

// OpenatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenatObjects struct {
	OpenatPrograms
	OpenatMaps
	OpenatVariables
}

func (o *OpenatObjects) Close() error {
	return _OpenatClose(
		&o.OpenatPrograms,
		&o.OpenatMaps,
	)
}

// OpenatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenatMaps struct {
	ExecveEvents     *ebpf.Map `ebpf:"execve_events"`
	ExecveTmpStorage *ebpf.Map `ebpf:"execve_tmp_storage"`
	OpenatEvents     *ebpf.Map `ebpf:"openat_events"`
	OpenatTmpStorage *ebpf.Map `ebpf:"openat_tmp_storage"`
}

func (m *OpenatMaps) Close() error {
	return _OpenatClose(
		m.ExecveEvents,
		m.ExecveTmpStorage,
		m.OpenatEvents,
		m.OpenatTmpStorage,
	)
}

// OpenatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenatVariables struct {
}

// OpenatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadOpenatObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenatPrograms struct {
	TraceEnterExecve *ebpf.Program `ebpf:"trace_enter_execve"`
	TraceEnterOpenat *ebpf.Program `ebpf:"trace_enter_openat"`
	TraceExitExecve  *ebpf.Program `ebpf:"trace_exit_execve"`
	TraceExitOpenat  *ebpf.Program `ebpf:"trace_exit_openat"`
}

func (p *OpenatPrograms) Close() error {
	return _OpenatClose(
		p.TraceEnterExecve,
		p.TraceEnterOpenat,
		p.TraceExitExecve,
		p.TraceExitOpenat,
	)
}

func _OpenatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed openat_bpfel.o
var _OpenatBytes []byte
