// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TraceAcceptArgsT struct {
	_    structs.HostLayout
	Addr uint64
}

type TraceConnectArgsT struct {
	_    structs.HostLayout
	Fd   int32
	Ip   uint32
	Port uint16
	_    [2]byte
}

type TraceExecveArgsT struct {
	_        structs.HostLayout
	Filename [128]int8
	Argv     [24][64]int8
	Envp     [24][64]int8
}

type TraceOpenatArgsT struct {
	_        structs.HostLayout
	Dfd      int32
	Flags    int32
	Filename [128]int8
}

type TracePtraceArgsT struct {
	_         structs.HostLayout
	Request   uint64
	TargetPid int32
	_         [4]byte
	Addr      uint64
}

// LoadTrace returns the embedded CollectionSpec for Trace.
func LoadTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Trace: %w", err)
	}

	return spec, err
}

// LoadTraceObjects loads Trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TraceObjects
//	*TracePrograms
//	*TraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraceSpecs struct {
	TraceProgramSpecs
	TraceMapSpecs
	TraceVariableSpecs
}

// TraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraceProgramSpecs struct {
	TraceEnterAccept4 *ebpf.ProgramSpec `ebpf:"trace_enter_accept4"`
	TraceEnterConnect *ebpf.ProgramSpec `ebpf:"trace_enter_connect"`
	TraceEnterExecve  *ebpf.ProgramSpec `ebpf:"trace_enter_execve"`
	TraceEnterOpenat  *ebpf.ProgramSpec `ebpf:"trace_enter_openat"`
	TraceEnterPtrace  *ebpf.ProgramSpec `ebpf:"trace_enter_ptrace"`
	TraceExitAccept4  *ebpf.ProgramSpec `ebpf:"trace_exit_accept4"`
	TraceExitConnect  *ebpf.ProgramSpec `ebpf:"trace_exit_connect"`
	TraceExitExecve   *ebpf.ProgramSpec `ebpf:"trace_exit_execve"`
	TraceExitOpenat   *ebpf.ProgramSpec `ebpf:"trace_exit_openat"`
	TraceExitPtrace   *ebpf.ProgramSpec `ebpf:"trace_exit_ptrace"`
}

// TraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraceMapSpecs struct {
	AcceptEvents      *ebpf.MapSpec `ebpf:"accept_events"`
	AcceptTmpStorage  *ebpf.MapSpec `ebpf:"accept_tmp_storage"`
	ConnectEvents     *ebpf.MapSpec `ebpf:"connect_events"`
	ConnectTmpStorage *ebpf.MapSpec `ebpf:"connect_tmp_storage"`
	ExecveEvents      *ebpf.MapSpec `ebpf:"execve_events"`
	ExecveHeap        *ebpf.MapSpec `ebpf:"execve_heap"`
	ExecveTmpStorage  *ebpf.MapSpec `ebpf:"execve_tmp_storage"`
	OpenatEvents      *ebpf.MapSpec `ebpf:"openat_events"`
	OpenatTmpStorage  *ebpf.MapSpec `ebpf:"openat_tmp_storage"`
	PtraceEvents      *ebpf.MapSpec `ebpf:"ptrace_events"`
	PtraceTmpStorage  *ebpf.MapSpec `ebpf:"ptrace_tmp_storage"`
}

// TraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraceVariableSpecs struct {
}

// TraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraceObjects struct {
	TracePrograms
	TraceMaps
	TraceVariables
}

func (o *TraceObjects) Close() error {
	return _TraceClose(
		&o.TracePrograms,
		&o.TraceMaps,
	)
}

// TraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraceMaps struct {
	AcceptEvents      *ebpf.Map `ebpf:"accept_events"`
	AcceptTmpStorage  *ebpf.Map `ebpf:"accept_tmp_storage"`
	ConnectEvents     *ebpf.Map `ebpf:"connect_events"`
	ConnectTmpStorage *ebpf.Map `ebpf:"connect_tmp_storage"`
	ExecveEvents      *ebpf.Map `ebpf:"execve_events"`
	ExecveHeap        *ebpf.Map `ebpf:"execve_heap"`
	ExecveTmpStorage  *ebpf.Map `ebpf:"execve_tmp_storage"`
	OpenatEvents      *ebpf.Map `ebpf:"openat_events"`
	OpenatTmpStorage  *ebpf.Map `ebpf:"openat_tmp_storage"`
	PtraceEvents      *ebpf.Map `ebpf:"ptrace_events"`
	PtraceTmpStorage  *ebpf.Map `ebpf:"ptrace_tmp_storage"`
}

func (m *TraceMaps) Close() error {
	return _TraceClose(
		m.AcceptEvents,
		m.AcceptTmpStorage,
		m.ConnectEvents,
		m.ConnectTmpStorage,
		m.ExecveEvents,
		m.ExecveHeap,
		m.ExecveTmpStorage,
		m.OpenatEvents,
		m.OpenatTmpStorage,
		m.PtraceEvents,
		m.PtraceTmpStorage,
	)
}

// TraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraceVariables struct {
}

// TracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracePrograms struct {
	TraceEnterAccept4 *ebpf.Program `ebpf:"trace_enter_accept4"`
	TraceEnterConnect *ebpf.Program `ebpf:"trace_enter_connect"`
	TraceEnterExecve  *ebpf.Program `ebpf:"trace_enter_execve"`
	TraceEnterOpenat  *ebpf.Program `ebpf:"trace_enter_openat"`
	TraceEnterPtrace  *ebpf.Program `ebpf:"trace_enter_ptrace"`
	TraceExitAccept4  *ebpf.Program `ebpf:"trace_exit_accept4"`
	TraceExitConnect  *ebpf.Program `ebpf:"trace_exit_connect"`
	TraceExitExecve   *ebpf.Program `ebpf:"trace_exit_execve"`
	TraceExitOpenat   *ebpf.Program `ebpf:"trace_exit_openat"`
	TraceExitPtrace   *ebpf.Program `ebpf:"trace_exit_ptrace"`
}

func (p *TracePrograms) Close() error {
	return _TraceClose(
		p.TraceEnterAccept4,
		p.TraceEnterConnect,
		p.TraceEnterExecve,
		p.TraceEnterOpenat,
		p.TraceEnterPtrace,
		p.TraceExitAccept4,
		p.TraceExitConnect,
		p.TraceExitExecve,
		p.TraceExitOpenat,
		p.TraceExitPtrace,
	)
}

func _TraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_bpfeb.o
var _TraceBytes []byte
