// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TraceExecveArgsT struct {
	_        structs.HostLayout
	Filename [128]int8
	Args     [256]int8
}

type TraceOpenatArgsT struct {
	_        structs.HostLayout
	Dfd      int32
	Flags    int32
	Filename [128]int8
}

// LoadTrace returns the embedded CollectionSpec for Trace.
func LoadTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Trace: %w", err)
	}

	return spec, err
}

// LoadTraceObjects loads Trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TraceObjects
//	*TracePrograms
//	*TraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraceSpecs struct {
	TraceProgramSpecs
	TraceMapSpecs
	TraceVariableSpecs
}

// TraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraceProgramSpecs struct {
	TraceEnterExecve *ebpf.ProgramSpec `ebpf:"trace_enter_execve"`
	TraceEnterOpenat *ebpf.ProgramSpec `ebpf:"trace_enter_openat"`
	TraceExitExecve  *ebpf.ProgramSpec `ebpf:"trace_exit_execve"`
	TraceExitOpenat  *ebpf.ProgramSpec `ebpf:"trace_exit_openat"`
}

// TraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraceMapSpecs struct {
	ExecveEvents     *ebpf.MapSpec `ebpf:"execve_events"`
	ExecveHeap       *ebpf.MapSpec `ebpf:"execve_heap"`
	ExecveTmpStorage *ebpf.MapSpec `ebpf:"execve_tmp_storage"`
	OpenatEvents     *ebpf.MapSpec `ebpf:"openat_events"`
	OpenatTmpStorage *ebpf.MapSpec `ebpf:"openat_tmp_storage"`
}

// TraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraceVariableSpecs struct {
}

// TraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraceObjects struct {
	TracePrograms
	TraceMaps
	TraceVariables
}

func (o *TraceObjects) Close() error {
	return _TraceClose(
		&o.TracePrograms,
		&o.TraceMaps,
	)
}

// TraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraceMaps struct {
	ExecveEvents     *ebpf.Map `ebpf:"execve_events"`
	ExecveHeap       *ebpf.Map `ebpf:"execve_heap"`
	ExecveTmpStorage *ebpf.Map `ebpf:"execve_tmp_storage"`
	OpenatEvents     *ebpf.Map `ebpf:"openat_events"`
	OpenatTmpStorage *ebpf.Map `ebpf:"openat_tmp_storage"`
}

func (m *TraceMaps) Close() error {
	return _TraceClose(
		m.ExecveEvents,
		m.ExecveHeap,
		m.ExecveTmpStorage,
		m.OpenatEvents,
		m.OpenatTmpStorage,
	)
}

// TraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraceVariables struct {
}

// TracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracePrograms struct {
	TraceEnterExecve *ebpf.Program `ebpf:"trace_enter_execve"`
	TraceEnterOpenat *ebpf.Program `ebpf:"trace_enter_openat"`
	TraceExitExecve  *ebpf.Program `ebpf:"trace_exit_execve"`
	TraceExitOpenat  *ebpf.Program `ebpf:"trace_exit_openat"`
}

func (p *TracePrograms) Close() error {
	return _TraceClose(
		p.TraceEnterExecve,
		p.TraceEnterOpenat,
		p.TraceExitExecve,
		p.TraceExitOpenat,
	)
}

func _TraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_bpfel.o
var _TraceBytes []byte
